In [1]:
import sys
sys.path.append("../../../repository")
import numpy as np

In [2]:
from src.pulsed_power_ml.models.gupta_model.gupta_clf import GuptaClassifier
from src.pulsed_power_ml.models.gupta_model.gupta_utils import read_power_data_base
from src.pulsed_power_ml.models.gupta_model.gupta_utils import read_parameters

from src.pulsed_power_ml.model_framework.data_io import read_training_files

In [3]:
power_db_file = "/home/thomas/projects/nilm_at_fair/repository/src/pulsed_power_ml/models/gupta_model/apparent_power_data_base.yml"
parameter_file = "/home/thomas/projects/nilm_at_fair/repository/src/pulsed_power_ml/models/gupta_model/parameters.yml"
data_folder = "/home/thomas/projects/nilm_at_fair/training_data/2022-10-25_training_data/tube/"

In [4]:
apparent_power_list = read_power_data_base(power_db_file)
parameter_dict = read_parameters(parameter_file)

In [5]:
clf = GuptaClassifier(
    background_n=parameter_dict["background_n"],
    fft_size_real=parameter_dict["fft_size"] / 2,
    sample_rate=parameter_dict["sample_rate"],
    n_known_appliances=len(parameter_dict["appliances"]) - 1,
    spectrum_type=2,
    n_peaks_max=3,
    apparent_power_list=apparent_power_list,
)

In [6]:
dummy_X = np.random.rand(9, 9)
dummy_y = np.array([[1, 0, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0, 0]] * 3)

In [7]:
clf.fit(X=dummy_X, y=dummy_y)

GuptaClassifier(apparent_power_list=[('fluorescent_0', 50.0),
                                     ('halogen_0', 45.9), ('led_0', 5.8)],
                n_known_appliances=3, n_peaks_max=3, spectrum_type=2)

In [8]:
data_array = read_training_files(data_folder,
                                 fft_size=parameter_dict["fft_size"])

In [9]:
state_vector_list = list()
for data_point in data_array:
    state_vector = clf.predict(data_point)
    state_vector_list.append(state_vector)

Event detected: Calculate feature vector


/home/thomas/.venv/nilm_at_fair/lib/python3.8/site-packages/scipy/optimize/_minpack_py.py:881: OptimizeWarning: Covariance of the parameters could not be estimated
  warnings.warn('Covariance of the parameters could not be estimated',


Event detected: Calculate feature vector


/home/thomas/.venv/nilm_at_fair/lib/python3.8/site-packages/scipy/optimize/_minpack_py.py:881: OptimizeWarning: Covariance of the parameters could not be estimated
  warnings.warn('Covariance of the parameters could not be estimated',


In [10]:
len(clf.background_vector)

25

In [11]:
state_vector_list

[array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0., 